#!/usr/bin/env python3
"""
Restore stripped diacritics in es, pt-br, tr, fr locales.
Whole-word, case-sensitive (preserving capitalization for sentence-start).
Avoids touching code/JSON-LD/URLs/brand names.
"""
import os, re

ROOT = "/home/user/workspace/winnersclub.com"

# Per-locale word fixes: ascii_word -> accented_word
# Pairs are matched as WHOLE WORDS only (word boundaries).
# Order matters: longer phrases first to avoid partial overlaps.

FIXES = {
    "es": [
        # Phrases first
        ("al Registrarte", "al registrarte"),
        ("Codigo Promo", "Código Promo"),
        # Words
        ("Codigo", "Código"),
        ("codigo", "código"),
        ("Codigos", "Códigos"),
        ("codigos", "códigos"),
        ("aqui", "aquí"),
        ("Aqui", "Aquí"),
        ("alli", "allí"),
        ("Alli", "Allí"),
        ("ahi", "ahí"),
        ("asi", "así"),
        ("Asi", "Así"),
        ("mas", "más"),  # CAREFUL — "mas" can be conjunction; check below
        ("ademas", "además"),
        ("Ademas", "Además"),
        ("despues", "después"),
        ("Despues", "Después"),
        ("solo", "sólo"),  # OPTIONAL — Spanish RAE allows both; SKIP this one
        ("tambien", "también"),
        ("Tambien", "También"),
        ("rapido", "rápido"),
        ("Rapido", "Rápido"),
        ("rapida", "rápida"),
        ("Rapida", "Rápida"),
        ("catalogo", "catálogo"),
        ("Catalogo", "Catálogo"),
        ("dia", "día"),
        ("Dia", "Día"),
        ("dias", "días"),
        ("Dias", "Días"),
        ("ano", "año"),  # CAREFUL — "ano" is also a word ("anus") — context matters
        ("anos", "años"),
        ("Anos", "Años"),
        ("pequeno", "pequeño"),
        ("pequena", "pequeña"),
        ("Espanol", "Español"),
        ("espanol", "español"),
        ("informacion", "información"),
        ("Informacion", "Información"),
        ("verificacion", "verificación"),
        ("Verificacion", "Verificación"),
        ("seccion", "sección"),
        ("Seccion", "Sección"),
        ("revision", "revisión"),
        ("Revision", "Revisión"),
        ("version", "versión"),
        ("Version", "Versión"),
        ("transaccion", "transacción"),
        ("Transaccion", "Transacción"),
        ("operacion", "operación"),
        ("Operacion", "Operación"),
        ("opcion", "opción"),
        ("Opcion", "Opción"),
        ("opciones", "opciones"),  # no change but keep stable
        ("region", "región"),
        ("Region", "Región"),
        ("regiones", "regiones"),  # no change
        ("licitacion", "licitación"),
        ("garantia", "garantía"),
        ("Garantia", "Garantía"),
        ("politica", "política"),
        ("Politica", "Política"),
        ("publico", "público"),
        ("Publico", "Público"),
        ("publica", "pública"),
        ("Publica", "Pública"),
        ("musica", "música"),
        ("Musica", "Música"),
        ("electronico", "electrónico"),
        ("electronica", "electrónica"),
        ("metodo", "método"),
        ("Metodo", "Método"),
        ("metodos", "métodos"),
        ("Metodos", "Métodos"),
        ("seguridad", "seguridad"),  # no change
        ("limite", "límite"),
        ("Limite", "Límite"),
        ("limites", "límites"),
        ("Limites", "Límites"),
        ("rapidisimo", "rapidísimo"),
        ("facil", "fácil"),
        ("Facil", "Fácil"),
        ("dificil", "difícil"),
        ("Dificil", "Difícil"),
        ("util", "útil"),
        ("Util", "Útil"),
        ("Atras", "Atrás"),
        ("atras", "atrás"),
        ("mas alla", "más allá"),
        ("alla", "allá"),
        ("habia", "había"),
        ("podria", "podría"),
        ("Podria", "Podría"),
        ("seria", "sería"),
        ("Seria", "Sería"),
        ("vendra", "vendrá"),
        ("estara", "estará"),
        ("Estara", "Estará"),
        ("esta aqui", "está aquí"),
        ("Esta aqui", "Está aquí"),
        ("Maximo", "Máximo"),
        ("maximo", "máximo"),
        ("Minimo", "Mínimo"),
        ("minimo", "mínimo"),
        ("Practico", "Práctico"),
        ("practico", "práctico"),
        ("Practica", "Práctica"),
        ("practica", "práctica"),
        ("automatico", "automático"),
        ("Automatico", "Automático"),
        ("America", "América"),
        ("Mexico", "México"),  # in body copy; URLs unchanged because they're inside <a href>
        ("Peru", "Perú"),
        ("Brasil", "Brasil"),  # no change
        ("Espana", "España"),
        ("Aleman", "Alemán"),
        ("aleman", "alemán"),
        ("Curacao", "Curaçao"),
        ("numero", "número"),
        ("Numero", "Número"),
        ("numeros", "números"),
        ("Numeros", "Números"),
        ("ultimo", "último"),
        ("Ultimo", "Último"),
        ("ultima", "última"),
        ("Ultima", "Última"),
        ("ultimos", "últimos"),
        ("ultimas", "últimas"),
        ("rapidez", "rapidez"),  # no change
        ("Telegrafo", "Telégrafo"),
        ("telefono", "teléfono"),
        ("Telefono", "Teléfono"),
        ("ingles", "inglés"),
        ("Ingles", "Inglés"),
        ("frances", "francés"),
        ("Frances", "Francés"),
        ("portugues", "portugués"),
        ("Portugues", "Portugués"),
        ("japones", "japonés"),
        ("Japones", "Japonés"),
        ("chino", "chino"),  # no change
        ("vietnamita", "vietnamita"),  # no change
        ("politico", "político"),
        ("Politico", "Político"),
        ("economia", "economía"),
        ("Economia", "Economía"),
        ("energia", "energía"),
        ("Energia", "Energía"),
        ("pagina", "página"),
        ("Pagina", "Página"),
        ("paginas", "páginas"),
        ("Paginas", "Páginas"),
        ("crypto", "crypto"),  # no change, English loanword
        ("anonimo", "anónimo"),
        ("Anonimo", "Anónimo"),
        ("propio", "propio"),  # no change
        ("calculo", "cálculo"),
        ("Calculo", "Cálculo"),
        ("calculos", "cálculos"),
        ("Calculos", "Cálculos"),
        ("rapido", "rápido"),
        ("solido", "sólido"),
        ("Solido", "Sólido"),
        ("solida", "sólida"),
        ("Solida", "Sólida"),
        ("liquido", "líquido"),
        ("Liquido", "Líquido"),
        ("transparente", "transparente"),  # no change
        ("oxigeno", "oxígeno"),
        ("invertir", "invertir"),  # no change
        ("apuesta", "apuesta"),  # no change
        ("Apuesta", "Apuesta"),  # no change
        ("rollover", "rollover"),  # no change
        ("hasta", "hasta"),  # no change
        ("Hasta", "Hasta"),  # no change
        # Reflexive 'se' adds tilde when stressed
        ("Registrate", "Regístrate"),
        ("registrate", "regístrate"),
        ("Estan", "Están"),
        ("estan", "están"),
        ("Esten", "Estén"),
        ("Esta", "Está"),  # CAREFUL — "esta" (this, fem) vs "está" (is). Word-boundary alone insufficient.
        # SKIP "Esta"/"esta" since they're ambiguous — context-sensitive
    ],
    "pt-br": [
        ("Codigo Promo", "Código Promo"),
        ("Codigo", "Código"),
        ("codigo", "código"),
        ("Codigos", "Códigos"),
        ("codigos", "códigos"),
        ("voce", "você"),
        ("Voce", "Você"),
        ("voces", "vocês"),
        ("Voces", "Vocês"),
        ("tambem", "também"),
        ("Tambem", "Também"),
        ("nao", "não"),
        ("Nao", "Não"),
        ("entao", "então"),
        ("Entao", "Então"),
        ("informacao", "informação"),
        ("Informacao", "Informação"),
        ("informacoes", "informações"),
        ("Informacoes", "Informações"),
        ("verificacao", "verificação"),
        ("Verificacao", "Verificação"),
        ("transacao", "transação"),
        ("Transacao", "Transação"),
        ("transacoes", "transações"),
        ("Transacoes", "Transações"),
        ("operacao", "operação"),
        ("Operacao", "Operação"),
        ("opcao", "opção"),
        ("Opcao", "Opção"),
        ("opcoes", "opções"),
        ("Opcoes", "Opções"),
        ("regiao", "região"),
        ("Regiao", "Região"),
        ("regioes", "regiões"),
        ("Regioes", "Regiões"),
        ("secao", "seção"),
        ("Secao", "Seção"),
        ("secoes", "seções"),
        ("Secoes", "Seções"),
        ("cassino", "cassino"),  # no change
        ("Cassino", "Cassino"),  # no change
        ("Sao", "São"),  # São Paulo etc.
        ("sao", "são"),  # they are
        ("mae", "mãe"),
        ("Mae", "Mãe"),
        ("pai", "pai"),  # no change
        ("dia", "dia"),  # no change
        ("dias", "dias"),  # no change
        ("ate", "até"),
        ("Ate", "Até"),
        ("apos", "após"),
        ("Apos", "Após"),
        ("ja", "já"),
        ("Ja", "Já"),
        ("la", "lá"),
        ("ai", "aí"),
        ("Ai", "Aí"),
        ("aqui", "aqui"),  # no change
        ("Aqui", "Aqui"),
        ("alem", "além"),
        ("Alem", "Além"),
        ("porem", "porém"),
        ("Porem", "Porém"),
        ("tres", "três"),
        ("Tres", "Três"),
        ("ingles", "inglês"),
        ("Ingles", "Inglês"),
        ("portugues", "português"),
        ("Portugues", "Português"),
        ("frances", "francês"),
        ("Frances", "Francês"),
        ("japones", "japonês"),
        ("Japones", "Japonês"),
        ("politica", "política"),
        ("Politica", "Política"),
        ("publico", "público"),
        ("Publico", "Público"),
        ("publica", "pública"),
        ("Publica", "Pública"),
        ("musica", "música"),
        ("Musica", "Música"),
        ("rapido", "rápido"),
        ("Rapido", "Rápido"),
        ("rapida", "rápida"),
        ("Rapida", "Rápida"),
        ("facil", "fácil"),
        ("Facil", "Fácil"),
        ("dificil", "difícil"),
        ("Dificil", "Difícil"),
        ("util", "útil"),
        ("Util", "Útil"),
        ("metodo", "método"),
        ("Metodo", "Método"),
        ("metodos", "métodos"),
        ("Metodos", "Métodos"),
        ("limite", "limite"),  # no change
        ("Limite", "Limite"),  # no change
        ("maximo", "máximo"),
        ("Maximo", "Máximo"),
        ("minimo", "mínimo"),
        ("Minimo", "Mínimo"),
        ("ultimo", "último"),
        ("Ultimo", "Último"),
        ("ultima", "última"),
        ("Ultima", "Última"),
        ("automatico", "automático"),
        ("Automatico", "Automático"),
        ("America", "América"),
        ("Curacao", "Curaçao"),
        ("numero", "número"),
        ("Numero", "Número"),
        ("numeros", "números"),
        ("Numeros", "Números"),
        ("pagina", "página"),
        ("Pagina", "Página"),
        ("paginas", "páginas"),
        ("Paginas", "Páginas"),
        ("garantia", "garantia"),  # no change
        ("estavel", "estável"),
        ("Estavel", "Estável"),
        ("nivel", "nível"),
        ("Nivel", "Nível"),
        ("niveis", "níveis"),
        ("Niveis", "Níveis"),
        ("disponivel", "disponível"),
        ("Disponivel", "Disponível"),
        ("possivel", "possível"),
        ("Possivel", "Possível"),
        ("responsavel", "responsável"),
        ("Responsavel", "Responsável"),
        ("acessivel", "acessível"),
        ("rapidez", "rapidez"),  # no change
        ("eletronico", "eletrônico"),
        ("Eletronico", "Eletrônico"),
        ("eletronica", "eletrônica"),
        ("Eletronica", "Eletrônica"),
        ("eletronicos", "eletrônicos"),
        ("acucar", "açúcar"),
        ("conteudo", "conteúdo"),
        ("Conteudo", "Conteúdo"),
        ("conferencia", "conferência"),
        ("agencia", "agência"),
        ("Agencia", "Agência"),
        ("emergencia", "emergência"),
        ("transparencia", "transparência"),
        ("Transparencia", "Transparência"),
        ("experiencia", "experiência"),
        ("Experiencia", "Experiência"),
        ("essencia", "essência"),
        ("ciencia", "ciência"),
        ("Ciencia", "Ciência"),
        ("usuario", "usuário"),
        ("Usuario", "Usuário"),
        ("usuarios", "usuários"),
        ("Usuarios", "Usuários"),
        ("relogio", "relógio"),
        ("Relogio", "Relógio"),
        ("Cadastre-se", "Cadastre-se"),  # no change
        ("cadastre-se", "cadastre-se"),
        ("crypto", "crypto"),
        ("Estao", "Estão"),
        ("estao", "estão"),
        ("Inicio", "Início"),
        ("inicio", "início"),
        ("Termino", "Término"),
        ("termino", "término"),
        ("Servico", "Serviço"),
        ("servico", "serviço"),
        ("Servicos", "Serviços"),
        ("servicos", "serviços"),
        ("Brasao", "Brasão"),
        ("ouro", "ouro"),  # no change
        ("dolar", "dólar"),
        ("Dolar", "Dólar"),
        ("dolares", "dólares"),
        ("Dolares", "Dólares"),
        ("ate o", "até o"),  # already covered by 'ate'
        ("apostar", "apostar"),  # no change
        ("perdido", "perdido"),  # no change
        ("ganho", "ganho"),  # no change
    ],
    "tr": [
        ("Stake Hakkinda", "Stake Hakkında"),
        ("Hakkinda", "Hakkında"),
        ("hakkinda", "hakkında"),
        ("Kayit Olurken", "Kayıt Olurken"),
        ("Kayit Ol", "Kayıt Ol"),
        ("Kayit", "Kayıt"),
        ("kayit", "kayıt"),
        ("Giris Yap", "Giriş Yap"),
        ("Giris", "Giriş"),
        ("giris", "giriş"),
        ("cikis", "çıkış"),
        ("Cikis", "Çıkış"),
        ("sart", "şart"),
        ("Sart", "Şart"),
        ("sartlar", "şartlar"),
        ("Sartlar", "Şartlar"),
        ("cevrim", "çevrim"),
        ("Cevrim", "Çevrim"),
        ("Turk", "Türk"),  # word; Turkce etc handled below
        ("turk", "türk"),
        ("Turkce", "Türkçe"),
        ("turkce", "türkçe"),
        ("Turkiye", "Türkiye"),
        ("turkiye", "türkiye"),
        ("ulke", "ülke"),
        ("Ulke", "Ülke"),
        ("ulkeler", "ülkeler"),
        ("Ulkeler", "Ülkeler"),
        ("oduller", "ödüller"),
        ("odul", "ödül"),
        ("Odul", "Ödül"),
        ("ode", "öde"),
        ("odeme", "ödeme"),
        ("Odeme", "Ödeme"),
        ("odemeler", "ödemeler"),
        ("Odemeler", "Ödemeler"),
        ("guvenli", "güvenli"),
        ("Guvenli", "Güvenli"),
        ("guvenlik", "güvenlik"),
        ("Guvenlik", "Güvenlik"),
        ("sifre", "şifre"),
        ("Sifre", "Şifre"),
        ("uye", "üye"),
        ("Uye", "Üye"),
        ("uyelik", "üyelik"),
        ("Uyelik", "Üyelik"),
        ("zellik", "özellik"),  # not safe — leave
        ("hosgeldin", "hoşgeldin"),
        ("Hosgeldin", "Hoşgeldin"),
        ("bonus", "bonus"),  # no change
        ("Bonus", "Bonus"),
        ("yuzde", "yüzde"),
        ("Yuzde", "Yüzde"),
        ("yontem", "yöntem"),
        ("Yontem", "Yöntem"),
        ("yontemler", "yöntemler"),
        ("Yontemler", "Yöntemler"),
        ("yon", "yön"),
        ("Yon", "Yön"),
        ("haftalik", "haftalık"),
        ("Haftalik", "Haftalık"),
        ("gunluk", "günlük"),
        ("Gunluk", "Günlük"),
        ("aylik", "aylık"),
        ("Aylik", "Aylık"),
        ("yillik", "yıllık"),
        ("Yillik", "Yıllık"),
        ("acik", "açık"),
        ("Acik", "Açık"),
        ("kapali", "kapalı"),
        ("Kapali", "Kapalı"),
        ("dogru", "doğru"),
        ("Dogru", "Doğru"),
        ("yanlis", "yanlış"),
        ("Yanlis", "Yanlış"),
        ("buyuk", "büyük"),
        ("Buyuk", "Büyük"),
        ("kucuk", "küçük"),
        ("Kucuk", "Küçük"),
        ("genis", "geniş"),
        ("Genis", "Geniş"),
        ("kapsam", "kapsam"),  # no change
        ("calismak", "çalışmak"),
        ("calisir", "çalışır"),
        ("yatirim", "yatırım"),
        ("Yatirim", "Yatırım"),
        ("cekim", "çekim"),
        ("Cekim", "Çekim"),
        ("cekimler", "çekimler"),
        ("para cekme", "para çekme"),
        ("Para cekme", "Para çekme"),
        ("baglanti", "bağlantı"),
        ("Baglanti", "Bağlantı"),
        ("hizli", "hızlı"),
        ("Hizli", "Hızlı"),
        ("hizmet", "hizmet"),  # no change
        ("yuksek", "yüksek"),
        ("Yuksek", "Yüksek"),
        ("dusuk", "düşük"),
        ("Dusuk", "Düşük"),
        ("dakika", "dakika"),  # no change
        ("saat", "saat"),  # no change
        ("ozel", "özel"),
        ("Ozel", "Özel"),
        ("zellikler", "özellikler"),
        ("gun", "gün"),
        ("Gun", "Gün"),
        ("gece", "gece"),  # no change
        ("once", "önce"),
        ("Once", "Önce"),
        ("sonra", "sonra"),  # no change
        ("Sonra", "Sonra"),
        ("simdi", "şimdi"),
        ("Simdi", "Şimdi"),
        ("hala", "hâlâ"),  # uncommon â, may skip
        ("istediginiz", "istediğiniz"),
        ("istek", "istek"),  # no change
        ("dort", "dört"),
        ("Dort", "Dört"),
        ("ucret", "ücret"),
        ("Ucret", "Ücret"),
        ("ucretsiz", "ücretsiz"),
        ("Ucretsiz", "Ücretsiz"),
        ("uzerinde", "üzerinde"),
        ("Uzerinde", "Üzerinde"),
        ("uzerinden", "üzerinden"),
        ("ust", "üst"),
        ("Ust", "Üst"),
        ("biraz", "biraz"),  # no change
        ("biraz once", "biraz önce"),
        ("sahip", "sahip"),  # no change
        ("calisma", "çalışma"),
        ("Calisma", "Çalışma"),
        ("gucluk", "güçlük"),
        ("guc", "güç"),
        ("Guc", "Güç"),
        ("guclu", "güçlü"),
        ("Guclu", "Güçlü"),
    ],
    "fr": [
        ("jusqu'a", "jusqu'à"),
        ("Jusqu'a", "Jusqu'à"),
        ("a l'inscription", "à l'inscription"),
        ("A l'inscription", "À l'inscription"),
        ("a propos de", "à propos de"),
        ("A propos de", "À propos de"),
        ("apres", "après"),
        ("Apres", "Après"),
        ("Reserves", "Réserves"),
        ("reserves", "réserves"),
        ("Reserve", "Réserve"),
        ("reserve", "réserve"),
        ("verifie", "vérifié"),
        ("Verifie", "Vérifié"),
        ("verifies", "vérifiés"),
        ("verifiee", "vérifiée"),
        ("verifiees", "vérifiées"),
        ("verification", "vérification"),
        ("Verification", "Vérification"),
        ("verifier", "vérifier"),
        ("verifiez", "vérifiez"),
        ("methode", "méthode"),
        ("Methode", "Méthode"),
        ("methodes", "méthodes"),
        ("Methodes", "Méthodes"),
        ("regle", "règle"),
        ("Regle", "Règle"),
        ("regles", "règles"),
        ("Regles", "Règles"),
        ("acces", "accès"),
        ("Acces", "Accès"),
        ("ces", "ces"),  # no change
        ("etape", "étape"),
        ("Etape", "Étape"),
        ("etapes", "étapes"),
        ("Etapes", "Étapes"),
        ("etat", "état"),
        ("Etat", "État"),
        ("etats", "états"),
        ("Etats", "États"),
        ("etre", "être"),
        ("Etre", "Être"),
        ("ete", "été"),
        ("Ete", "Été"),
        ("deja", "déjà"),
        ("Deja", "Déjà"),
        ("decembre", "décembre"),
        ("Decembre", "Décembre"),
        ("derniere", "dernière"),
        ("Derniere", "Dernière"),
        ("dernier", "dernier"),  # no change
        ("premiere", "première"),
        ("Premiere", "Première"),
        ("premier", "premier"),  # no change
        ("ferme", "fermé"),
        ("Ferme", "Fermé"),
        ("fermee", "fermée"),
        ("eleve", "élevé"),
        ("Eleve", "Élevé"),
        ("elevee", "élevée"),
        ("eleves", "élevés"),
        ("frequence", "fréquence"),
        ("Frequence", "Fréquence"),
        ("frequent", "fréquent"),
        ("frequents", "fréquents"),
        ("frequemment", "fréquemment"),
        ("genere", "généré"),
        ("Genere", "Généré"),
        ("genereux", "généreux"),
        ("general", "général"),
        ("General", "Général"),
        ("generale", "générale"),
        ("Generale", "Générale"),
        ("garantee", "garantie"),  # weird typo
        ("garanti", "garanti"),  # no change
        ("garantie", "garantie"),
        ("desole", "désolé"),
        ("desolee", "désolée"),
        ("ideal", "idéal"),
        ("Ideal", "Idéal"),
        ("ideale", "idéale"),
        ("integralite", "intégralité"),
        ("integrite", "intégrité"),
        ("integre", "intégré"),
        ("interesse", "intéressé"),
        ("interessant", "intéressant"),
        ("Interessant", "Intéressant"),
        ("interessants", "intéressants"),
        ("interessante", "intéressante"),
        ("interet", "intérêt"),
        ("Interet", "Intérêt"),
        ("interets", "intérêts"),
        ("Interets", "Intérêts"),
        ("interieur", "intérieur"),
        ("Interieur", "Intérieur"),
        ("inferieur", "inférieur"),
        ("Inferieur", "Inférieur"),
        ("superieur", "supérieur"),
        ("Superieur", "Supérieur"),
        ("priorite", "priorité"),
        ("Priorite", "Priorité"),
        ("prioritaire", "prioritaire"),  # no change
        ("securite", "sécurité"),
        ("Securite", "Sécurité"),
        ("etoile", "étoile"),
        ("Etoile", "Étoile"),
        ("etoiles", "étoiles"),
        ("equipe", "équipe"),
        ("Equipe", "Équipe"),
        ("equipes", "équipes"),
        ("equipement", "équipement"),
        ("ecart", "écart"),
        ("Ecart", "Écart"),
        ("ecarts", "écarts"),
        ("ecole", "école"),
        ("Ecole", "École"),
        ("evite", "évité"),
        ("eviter", "éviter"),
        ("eviterez", "éviterez"),
        ("element", "élément"),
        ("Element", "Élément"),
        ("elements", "éléments"),
        ("Elements", "Éléments"),
        ("important", "important"),  # no change
        ("disponible", "disponible"),  # no change
        ("favorable", "favorable"),  # no change
        ("activite", "activité"),
        ("Activite", "Activité"),
        ("activites", "activités"),
        ("Activites", "Activités"),
        ("societe", "société"),
        ("Societe", "Société"),
        ("societes", "sociétés"),
        ("controle", "contrôle"),
        ("Controle", "Contrôle"),
        ("controles", "contrôles"),
        ("controler", "contrôler"),
        ("etranger", "étranger"),
        ("Etranger", "Étranger"),
        ("etrangere", "étrangère"),
        ("etoffe", "étoffe"),
        ("ame", "âme"),
        ("Ame", "Âme"),
        ("hote", "hôte"),
        ("Hote", "Hôte"),
        ("hopital", "hôpital"),
        ("cote", "côté"),
        ("Cote", "Côté"),
        ("cotes", "côtés"),
        ("Cotes", "Côtés"),
        ("Cote a cote", "Côte à côte"),
        ("aupres", "auprès"),
        ("Aupres", "Auprès"),
        ("pres", "près"),
        ("Pres", "Près"),
        ("tres", "très"),
        ("Tres", "Très"),
        ("voila", "voilà"),
        ("Voila", "Voilà"),
        ("celebrite", "célébrité"),
        ("celebre", "célèbre"),
        ("Celebre", "Célèbre"),
        ("dela", "delà"),
        ("au-dela", "au-delà"),
        ("Au-dela", "Au-delà"),
        ("Curacao", "Curaçao"),
        ("francais", "français"),
        ("Francais", "Français"),
        ("Francaise", "Française"),
        ("francaise", "française"),
        ("anglais", "anglais"),  # no change
        ("Anglais", "Anglais"),
        ("portugais", "portugais"),
        ("Portugais", "Portugais"),
        ("espagnol", "espagnol"),
        ("Espagnol", "Espagnol"),
        ("japonais", "japonais"),
        ("Japonais", "Japonais"),
        ("Stake meriete", "Stake mérite"),
        ("merite", "mérite"),
        ("Merite", "Mérite"),
        ("preferes", "préférés"),
        ("preferee", "préférée"),
        ("prefere", "préféré"),
        ("Prefere", "Préféré"),
        ("preferences", "préférences"),
        ("complet", "complet"),  # no change
        ("complete", "complète"),
        ("Complete", "Complète"),
        ("completes", "complètes"),
        ("Completes", "Complètes"),
        ("conformite", "conformité"),
        ("Conformite", "Conformité"),
        ("compatible", "compatible"),  # no change
        ("Compatible", "Compatible"),
        ("realite", "réalité"),
        ("Realite", "Réalité"),
        ("reelle", "réelle"),
        ("Reelle", "Réelle"),
        ("reel", "réel"),
        ("Reel", "Réel"),
        ("reellement", "réellement"),
        ("regulier", "régulier"),
        ("Regulier", "Régulier"),
        ("reguliere", "régulière"),
        ("regulierement", "régulièrement"),
        ("reglement", "règlement"),
        ("Reglement", "Règlement"),
        ("reglementaire", "réglementaire"),
        ("Reglementaire", "Réglementaire"),
        ("repondre", "répondre"),
        ("Repondre", "Répondre"),
        ("repondu", "répondu"),
        ("reponse", "réponse"),
        ("Reponse", "Réponse"),
        ("reponses", "réponses"),
        ("succes", "succès"),
        ("Succes", "Succès"),
        ("interesse a", "intéressé à"),
        ("celebre", "célèbre"),
        ("epoque", "époque"),
        ("Epoque", "Époque"),
        ("operation", "opération"),
        ("Operation", "Opération"),
        ("operations", "opérations"),
        ("Operations", "Opérations"),
        ("offert", "offert"),  # no change
        ("offerte", "offerte"),
        ("offerts", "offerts"),
        ("decret", "décret"),
        ("decrets", "décrets"),
        ("defi", "défi"),
        ("Defi", "Défi"),
        ("declare", "déclaré"),
        ("Declare", "Déclaré"),
        ("declaration", "déclaration"),
        ("Declaration", "Déclaration"),
        ("debut", "début"),
        ("Debut", "Début"),
        ("debuts", "débuts"),
        ("decembre", "décembre"),
        ("nouveaute", "nouveauté"),
        ("Nouveaute", "Nouveauté"),
        ("nouveautes", "nouveautés"),
        ("autorite", "autorité"),
        ("Autorite", "Autorité"),
        ("autorites", "autorités"),
        ("Autorites", "Autorités"),
        ("autorise", "autorisé"),
        ("autorisee", "autorisée"),
        ("autoriser", "autoriser"),
        ("paiement", "paiement"),  # no change
        ("Paiement", "Paiement"),
        ("paiements", "paiements"),
        ("Paiements", "Paiements"),
        ("retrait", "retrait"),  # no change
        ("Retrait", "Retrait"),
        ("retraits", "retraits"),
        ("Retraits", "Retraits"),
        ("depot", "dépôt"),
        ("Depot", "Dépôt"),
        ("depots", "dépôts"),
        ("Depots", "Dépôts"),
        ("frais", "frais"),  # no change
        ("Frais", "Frais"),
        ("eviter", "éviter"),
        ("propose", "proposé"),
        ("Propose", "Proposé"),
        ("proposee", "proposée"),
        ("proposes", "proposés"),
        ("proposees", "proposées"),
        ("proposer", "proposer"),
        ("proposition", "proposition"),  # no change
        ("disponibilite", "disponibilité"),
        ("Disponibilite", "Disponibilité"),
        ("operee", "opérée"),
        ("operer", "opérer"),
        ("opere", "opéré"),
        ("Opere", "Opéré"),
    ],
}

# Build per-locale compiled regexes
def compile_fixes(pairs):
    """Returns list of (compiled_pattern, replacement)."""
    out = []
    for old, new in pairs:
        if old == new:
            continue
        pat = re.compile(r'\b' + re.escape(old) + r'\b')
        out.append((pat, new))
    return out

# Protected regions: don't touch script/style/JSON-LD/code/URLs/lang attr/hreflang/option values
PROTECT_RE = re.compile(
    r'(<script[^>]*>.*?</script>'
    r'|<style[^>]*>.*?</style>'
    r'|<!--.*?-->'
    r'|href="[^"]*"'
    r'|src="[^"]*"'
    r'|content="https?://[^"]*"'  # OG URLs
    r'|hreflang="[^"]*"'
    r'|lang="[^"]*"'
    r'|class="[^"]*"'
    r'|id="[^"]*"'
    r'|data-[a-zA-Z-]+="[^"]*"'
    r'|<code[^>]*>.*?</code>'
    r')',
    re.S | re.I,
)

def apply_fixes_to_text(text, compiled_fixes):
    """Apply fixes, but skip protected regions."""
    parts = []
    last = 0
    for m in PROTECT_RE.finditer(text):
        # Process the text before this protected region
        chunk = text[last:m.start()]
        for pat, new in compiled_fixes:
            chunk = pat.sub(new, chunk)
        parts.append(chunk)
        # Append the protected region unchanged
        parts.append(m.group(0))
        last = m.end()
    # Tail
    tail = text[last:]
    for pat, new in compiled_fixes:
        tail = pat.sub(new, tail)
    parts.append(tail)
    return "".join(parts)


def walk(loc_dir):
    for root, dirs, files in os.walk(loc_dir):
        for f in files:
            if f.endswith(".html"):
                yield os.path.join(root, f)


def main():
    total = 0
    for loc, pairs in FIXES.items():
        loc_path = os.path.join(ROOT, loc)
        if not os.path.isdir(loc_path):
            print(f"  {loc}: directory missing, skipping")
            continue
        cfixes = compile_fixes(pairs)
        n = 0
        for p in walk(loc_path):
            s = open(p, encoding="utf-8").read()
            new_s = apply_fixes_to_text(s, cfixes)
            if new_s != s:
                open(p, "w", encoding="utf-8").write(new_s)
                n += 1
        total += n
        print(f"  {loc}: {n} files updated")
    print(f"Total: {total}")

if __name__ == "__main__":
    main()
